apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stable-diffusion-ui.fullname" . }}
  labels:
    {{- include "stable-diffusion-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "stable-diffusion-ui.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stable-diffusion-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stable-diffusion-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "stable-diffusion-ui.fullname" . }}-repositories
              mountPath: /home/webui/stable-diffusion-webui/repositories/
            - name: {{ include "stable-diffusion-ui.fullname" . }}-venv
              mountPath: /home/webui/stable-diffusion-webui/venv/
            - name: {{ include "stable-diffusion-ui.fullname" . }}-cache
              mountPath: /home/webui/.cache
            - name: {{ include "stable-diffusion-ui.fullname" . }}-local
              mountPath: /home/webui/.local
            - name: {{ include "stable-diffusion-ui.fullname" . }}-models
              mountPath: /home/webui/stable-diffusion-webui/models/
            - name: {{ include "stable-diffusion-ui.fullname" . }}-torch
              mountPath: /home/webui/.torch
            - name: {{ include "stable-diffusion-ui.fullname" . }}-embeddings
              mountPath: /home/webui/stable-diffusion-webui/embeddings/
          env:
            - name: COMMANDLINE_ARGS
              value: {{ .Values.commandlineArgs }}
      volumes:
        - name: {{ include "stable-diffusion-ui.fullname" . }}-repositories
          persistentVolumeClaim:
            claimName: {{ include "stable-diffusion-ui.fullname" . }}-repositories
        - name: {{ include "stable-diffusion-ui.fullname" . }}-venv
          persistentVolumeClaim:
            claimName: {{ include "stable-diffusion-ui.fullname" . }}-venv
        - name: {{ include "stable-diffusion-ui.fullname" . }}-cache
          persistentVolumeClaim:
            claimName: {{ include "stable-diffusion-ui.fullname" . }}-cache
        - name: {{ include "stable-diffusion-ui.fullname" . }}-local
          persistentVolumeClaim:
            claimName: {{ include "stable-diffusion-ui.fullname" . }}-local
        - name: {{ include "stable-diffusion-ui.fullname" . }}-models
          persistentVolumeClaim:
            claimName: {{ include "stable-diffusion-ui.fullname" . }}-models
        - name: {{ include "stable-diffusion-ui.fullname" . }}-torch
          persistentVolumeClaim:
            claimName: {{ include "stable-diffusion-ui.fullname" . }}-torch
        - name: {{ include "stable-diffusion-ui.fullname" . }}-embeddings
          persistentVolumeClaim:
            claimName: {{ include "stable-diffusion-ui.fullname" . }}-embeddings
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      runtimeClassName: {{ .Values.runtimeClassName }}
