apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stable-diffusion-ui.fullname" . }}-models
  labels:
    {{- include "stable-diffusion-ui.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
  storageClassName: {{ .Values.persistence.models.storageClass }}