apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stable-diffusion-ui.fullname" . }}
  labels:
    {{- include "stable-diffusion-ui.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
