apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stable-diffusion-ui.fullname" . }}-venv
  labels:
    {{- include "stable-diffusion-ui.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.venv.size }}
  storageClassName: {{ .Values.persistence.venv.storageClass }}
