apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stable-diffusion-ui.fullname" . }}-cache
  labels:
    {{- include "stable-diffusion-ui.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
  storageClassName: {{ .Values.persistence.cache.storageClass }}
status: {}
