services:

  webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50005:7860"
    # gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - data:/home/webui
    environment:
      - COMMANDLINE_ARGS=--listen 0.0.0.0 --port 7860

volumes:
  data:
