services:

  webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50005:8080"
    # gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]