services:

  webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50005:8080"
    # gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility