services:

  webui:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 7860  # gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - data:/home/webui
    environment:
      - COMMANDLINE_ARGS=--listen --api --enable-insecure-extension-access

volumes:
  data:
