apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: webui
    spec:
      containers:
        - env:
            - name: COMMANDLINE_ARGS
              value: --listen  --enable-insecure-extension-access
          image: harbor.devops-tools.apoorva64.com/stable-diffusion/stable-diffusion@sha256:f632ff8365f3d48639f7b0bf703f1a66bffccf90fdd66298a827a1f550307378
          imagePullPolicy: IfNotPresent
          name: webui
          ports:
            - containerPort: 7860
          resources: { }
          volumeMounts:
            - mountPath: /home/webui
              name: webui-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: webui-claim0
          persistentVolumeClaim:
            claimName: webui-claim0
status: { }
