name: ci

on:
  push:
    branches:
      - 'master'


jobs:
  docker:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.devops-tools.apoorva64.com
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: harbor.devops-tools.apoorva64.com/stable-diffusion/stable-diffusion:latest,harbor.devops-tools.apoorva64.com/stable-diffusion/stable-diffusion:${{ github.sha }}