name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Helm Chart to ChartMuseum
        uses: bsord/helm-push@v4.1.0
        with:
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          useOCIRegistry: true
          registry-url: oci://harbor.devops-tools.apoorva64.com/stable-diffusion
          force: true
          chart-folder: charts/stable-diffusion-ui